### ISSUE TITLE
fatal should have same signature as println

### ISSUE THREAD

**Issue by Zamiell** [hgalant/fatal.rs#1]
Hello, and thanks for the library.

I'm using `fatal::fatal`, but its annoying that it only accepts one argument.
Shouldn't the `fatal` function have the same signature as the `println` function?

**Comment by hgalant** [comment]
Hey James,

The macro is indeed [variadic](https://docs.rs/fatal/latest/fatal/macro.fatal.html#:~:text=(%24(%24arg%3Att)*)%20%3D%3E%20%7B%20...%20%7D%3B) just like `println`, maybe your IDE had issues displaying that? Please try again and see if you get any errors from the actual compiler, and if you do please post the code you tried.

If it's an IDE issue I can report that it's working fine on VSCode with rust-analyzer, and it even understands that it's a format string.

**Comment by Zamiell** [comment]
Ok, my mistake. Sorry to bother.
